package com/mapper;

import com/dataobject.CommodityDO;
import com/dataobject.CommodityDOExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface CommodityDOMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table commodity
     *
     * @mbggenerated
     */
    int countByExample(CommodityDOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table commodity
     *
     * @mbggenerated
     */
    int deleteByExample(CommodityDOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table commodity
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table commodity
     *
     * @mbggenerated
     */
    int insert(CommodityDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table commodity
     *
     * @mbggenerated
     */
    int insertSelective(CommodityDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table commodity
     *
     * @mbggenerated
     */
    List<CommodityDO> selectByExample(CommodityDOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table commodity
     *
     * @mbggenerated
     */
    CommodityDO selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table commodity
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") CommodityDO record, @Param("example") CommodityDOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table commodity
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") CommodityDO record, @Param("example") CommodityDOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table commodity
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(CommodityDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table commodity
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(CommodityDO record);
}